%% Set parameters
bat_list = {'Tb104'};
times_location = ['S:\Smotherman_Lab\Auditory cortex\',bat_list,'\Spiketimes\'];
sr = 40000;
channels_available = 3;
save_path = 'C:\Users\kbakshi\Documents\Data\STRF Analysis\';
shank_pos = xlsread('Shank Position.xlsx');

strf_table(1,:) = {'Bat', 'Experimental_Site', 'RC_Location', 'Depth', 'Peak_Excitatory_Frequency',...
    'Latency_At_Peak', 'Peak_Inhibitory_Frequency', 'Latency_At_Min', 'Peak_Firing_Rate',...
    'Excitatory_Spectral_BW', 'Excitatory_Temporal_BW',...
    'Inhibitory_Spectral_BW', 'Inhibitory_Temporal_BW', 'Spectral_max_MTF',...
    'Temporal_max_MTF', 'Spectral_cutoff_MTF', 'Temporal_cutoff_MTF'};
iter = 2;

for bat_num = 1:numel(bat_list)
    site_number = 10;
    for site = 1:site_number
        %% Import Data, preprocess, and extract spike times
        load(strjoin(['S:\Smotherman_Lab\Auditory cortex\',string(bat_list(:,bat_num)),...
            '\Matfile\',num2str(site),'_dmr\event.mat'], ''));
        marker = importdata(strjoin(['S:\Smotherman_Lab\Auditory cortex\',string(bat_list(:,bat_num)),...
            '\Data\',string(bat_list(:,bat_num)),'_',num2str(site),'_marker_tc.mat'],''));
        for channel = 1:channels_available
            spikes = readmatrix(strjoin(...
                [times_location,num2str(site),'_dmr_chn',num2str(channel),'_times.txt'], ''));
            spikes = spikes(:,1);
            spikes(spikes < ts(1,1)) = [];
            spikes(spikes > ts(end,1)) = [];
            depth = marker.depth-shank_pos(channel,1);
            %% Find STRF
            spk = spikes * 1000;
            spiketimes{1}=spk;
            processdata
            STA=DMRcells.STA;
            STA_avg=mean(STA(:));
            STA_stdev=std(STA(:))*3;
            minus_STA_stdev=STA_stdev*-1;
            STA(STA > minus_STA_stdev & STA < STA_stdev) = 0;
            [col,row]=find(STA==max(STA(:)));
            latency=taxis(row);
            peak_freq=faxis(col)/1000;
            [col,row]=find(STA==min(STA(:)));
            min_peak_freq = faxis(col)/1000;
            min_latency = taxis(row);
            [e_spectralBW, e_temporalBW, i_spectralBW, i_temporalBW] = findSTRFbw(STA, taxis, faxis);

            %% Create STRF Figure
            [fig1, maxFR] = plotMuASTRF(STA, taxis, faxis, X, depth,...
                    latency, peak_freq, site, channel);
            exportgraphics(fig1, strjoin([save_path,string(bat_list(:,bat_num)),...
                '\Site ',num2str(site),' Chn ',num2str(channel),' STRF.jpg'],''),...
                'Resolution', 300)
            save(strjoin([save_path,string(bat_list(:,bat_num)),...
                '\Site ',num2str(site),' Chn ',num2str(channel),' STA'],''),...
                'STA')
            save(strjoin([save_path,string(bat_list(:,bat_num)),...
                '\Site ',num2str(site),' Chn ',num2str(channel),' faxis'],''),...
                'faxis')
            save(strjoin([save_path,string(bat_list(:,bat_num)),...
                '\Site ',num2str(site),' Chn ',num2str(channel),' taxis'],''),...
                'taxis')
            %% Generate modulation functions
            [MTF, tempmod, specmod] = STRF2MTF(STA, taxis, X);
            [fig2, specmod_max, tempmod_max, specmod_cut, tempmod_cut] = plotMTF(MTF, tempmod, specmod);
            sgtitle(['Site ',num2str(site), ' Chn ',num2str(channel),' MUA MTF'], 'Fontweight', 'bold')
            exportgraphics(fig2,...
                strjoin([save_path,string(bat_list(:,bat_num)),...
                '\Site ',num2str(site),' Chn ',num2str(channel),' MTF.jpg'],''),...
                'Resolution', 300)
            save(strjoin([save_path,string(bat_list(:,bat_num)),...
                '\Site ',num2str(site),' Chn ',num2str(channel),' MTF'],''),...
                'MTF')
            save(strjoin([save_path,string(bat_list(:,bat_num)),...
                '\Site ',num2str(site),' Chn ',num2str(channel),' specmod'],''),...
                'specmod')
            save(strjoin([save_path,string(bat_list(:,bat_num)),...
                '\Site ',num2str(site),' Chn ',num2str(channel),' tempmod'],''),...
                'tempmod')
            close all
            
            if channel < 17
                RC = marker.rostro_caudal - 250;
            else
                RC = marker.rostro_caudal;
            end
            
            strf_table(iter,:) = {bat_list(bat_num),...
                ['Site ', num2str(site), 'Channel ', num2str(channel)],...
                RC, depth, peak_freq, latency, min_peak_freq,...
                min_latency, maxFR, e_spectralBW,...
                e_temporalBW, i_spectralBW, i_temporalBW, specmod_max,...
                tempmod_max, specmod_cut, tempmod_cut};
            iter = iter+1;
        end
            clearvars -except bat_list times_location sr b a...
                channels_available channel save_path...
                ts marker shank_pos d site bat_num cutoff strf_table...
                iter
    end    
end
save([save_path, 'Tb104_STRF_data_full.mat'], 'strf_table')